version: '2'
services:
  testmicro-app:
    image: testmicro
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testmicro-postgresql:5432/testmicro
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  testmicro-postgresql:
    extends:
      file: postgresql.yml
      service: testmicro-postgresql
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
